{
    "name": "Construction Site Management",
    "version": "14.0.1.0.0",
    "category": "Operations/Construction",
    "license": "AGPL-3",
    "summary": "Advanced management features for cstr sites",
    "author": "Espadas",
    "depends": [
        "hr",
        "stock",
        "account",
        "project",
        "purchase",
        "website",
    ],
    "data": [
        "security/ir.model.access.csv",
        "views/actions.xml",
        "views/menus.xml",
        "views/cstr_shifit_views.xml",
        "views/cstr_project_views.xml",
        "views/cstr_work_views.xml",
        "views/invoice_views.xml",
        "views/materials.xml",
    ],
    "installable": True,
    "application": True,
    "auto_install": False,
}
