from . import cstr_shift
from . import hr_employee
from . import cstr_work
from . import cstr_work_line
from . import project
from . import cstr_materials
from . import supplier
from . import cstr_invoice
from . import cstr_materials_budget
